name: Build NW.js App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build app files
        run: |
          npm run clean
          mkdir dist
          xcopy src dist /E /I /Y
          xcopy data dist\data /E /I /Y
          copy package.json dist\package.json

      - name: Package NW.js app (EXE)
        run: npx nwbuild --src dist --out dist/build --platform win64 --flavor normal

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: bookblisss-win64
          path: dist/build/**
